import { stickyHeader } from './header/header';
import { burger } from './burger/burger';
import { navigation } from './nav/nav';
import { animatedHome } from './section-first-screen/section-first-screen';
import { parallax }  from './section-about/section-about';
import { sliderStaff }  from './section-staff/section-staff';
import { sliderTestimonials }  from './section-testimonials/section-testimonials';
import { sliderGallery }  from './section-gallery/section-gallery';
import { initMap } from './section-contacts/section-contacts';
import { showServicesImg } from './section-services/section-services';
import { moveUp } from './footer/footer';
stickyHeader();
burger();
navigation();
animatedHome();
parallax();
showServicesImg();
sliderStaff();
sliderTestimonials();
sliderGallery();
initMap();
moveUp();
